name: build
on:
  push:
    branches: [main]

env:
  DOCKER_HOST: tcp://172.17.0.1:2375

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login forgejo.int.wome.nz -u laale --password-stdin
          docker build -t forgejo.int.wome.nz/laale/resu:latest .
          docker push forgejo.int.wome.nz/laale/resu:latest
