-- Consolidated SQLite schema for the AOWeb API (final state, no migration cruft).
--
-- Type names BOOLEAN / TIMESTAMPTZ / JSONB / BIGINT are kept verbatim from the
-- PostgreSQL schema on purpose: src/sqliteDb.ts reads the declared column type
-- back from SQLite to normalize row values into the same JS shapes the `pg`
-- driver produces (boolean, Date, parsed JSON, string).
--
-- UUIDs are TEXT generated by the DEFAULT expression below (a v4 UUID built
-- from randomblob, since SQLite has no gen_random_uuid()). Timestamps are
-- ISO-8601 UTC text ('YYYY-MM-DDTHH:MM:SS.SSSZ'), so lexicographic comparison
-- matches chronological order; NOW() in queries is provided by a registered
-- SQL function returning the same format.

CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    name TEXT NOT NULL,
    name_sanitized TEXT,
    password TEXT,
    email TEXT UNIQUE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    disabled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS characters (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    id_clase INTEGER NOT NULL DEFAULT 0,
    map_id INTEGER NOT NULL DEFAULT 1,
    pos_x INTEGER NOT NULL DEFAULT 50,
    pos_y INTEGER NOT NULL DEFAULT 50,
    gold INTEGER NOT NULL DEFAULT 0,
    id_head INTEGER NOT NULL DEFAULT 0,
    id_last_head INTEGER NOT NULL DEFAULT 0,
    id_last_body INTEGER NOT NULL DEFAULT 0,
    id_last_helmet INTEGER NOT NULL DEFAULT 0,
    id_last_weapon INTEGER NOT NULL DEFAULT 0,
    id_last_shield INTEGER NOT NULL DEFAULT 0,
    id_helmet INTEGER NOT NULL DEFAULT 0,
    id_weapon INTEGER NOT NULL DEFAULT 0,
    id_shield INTEGER NOT NULL DEFAULT 0,
    id_body INTEGER NOT NULL DEFAULT 0,
    id_item_weapon INTEGER NOT NULL DEFAULT 0,
    id_item_body INTEGER NOT NULL DEFAULT 0,
    id_item_shield INTEGER NOT NULL DEFAULT 0,
    id_item_helmet INTEGER NOT NULL DEFAULT 0,
    id_item_arrow INTEGER NOT NULL DEFAULT 0,
    spells_acertados INTEGER NOT NULL DEFAULT 0,
    spells_errados INTEGER NOT NULL DEFAULT 0,
    hp INTEGER NOT NULL DEFAULT 0,
    max_hp INTEGER NOT NULL DEFAULT 0,
    mana INTEGER NOT NULL DEFAULT 0,
    max_mana INTEGER NOT NULL DEFAULT 0,
    hunger INTEGER NOT NULL DEFAULT 100,
    thirst INTEGER NOT NULL DEFAULT 100,
    stamina INTEGER NOT NULL DEFAULT 100,
    max_stamina INTEGER NOT NULL DEFAULT 100,
    envenenado INTEGER NOT NULL DEFAULT 0,
    skills TEXT NOT NULL DEFAULT '[]',
    skill_exp TEXT NOT NULL DEFAULT '[]',
    pets TEXT NOT NULL DEFAULT '[]',
    id_raza INTEGER NOT NULL DEFAULT 0,
    id_genero INTEGER NOT NULL DEFAULT 0,
    muerto BOOLEAN NOT NULL DEFAULT FALSE,
    min_hit INTEGER NOT NULL DEFAULT 0,
    max_hit INTEGER NOT NULL DEFAULT 0,
    attr_fuerza INTEGER NOT NULL DEFAULT 0,
    attr_agilidad INTEGER NOT NULL DEFAULT 0,
    attr_inteligencia INTEGER NOT NULL DEFAULT 0,
    attr_carisma INTEGER NOT NULL DEFAULT 0,
    attr_constitucion INTEGER NOT NULL DEFAULT 0,
    puntos_atributo INTEGER NOT NULL DEFAULT 0,
    privileges INTEGER NOT NULL DEFAULT 0,
    count_killed INTEGER NOT NULL DEFAULT 0,
    count_die INTEGER NOT NULL DEFAULT 0,
    exp INTEGER NOT NULL DEFAULT 0,
    exp_next_level INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 0,
    banned TIMESTAMPTZ,
    ip TEXT,
    dead BOOLEAN NOT NULL DEFAULT FALSE,
    criminal BOOLEAN NOT NULL DEFAULT FALSE,
    faction TEXT NOT NULL DEFAULT 'none' CHECK (faction IN ('none', 'armada', 'caos')),
    navegando BOOLEAN NOT NULL DEFAULT FALSE,
    npc_matados INTEGER NOT NULL DEFAULT 0,
    ciudadanos_matados INTEGER NOT NULL DEFAULT 0,
    criminales_matados INTEGER NOT NULL DEFAULT 0,
    fianza INTEGER NOT NULL DEFAULT 0,
    home_map INTEGER NOT NULL DEFAULT 1,
    home_x INTEGER NOT NULL DEFAULT 54,
    home_y INTEGER NOT NULL DEFAULT 60,
    faction_score_armada INTEGER NOT NULL DEFAULT 0,
    faction_score_caos INTEGER NOT NULL DEFAULT 0,
    faction_rank_armada INTEGER NOT NULL DEFAULT 0,
    faction_rank_caos INTEGER NOT NULL DEFAULT 0,
    faction_rewards_armada INTEGER NOT NULL DEFAULT 0,
    faction_rewards_caos INTEGER NOT NULL DEFAULT 0,
    connected BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    clan_id TEXT REFERENCES clans(id) ON DELETE SET NULL,
    jail_minutes INTEGER NOT NULL DEFAULT 0,
    jail_reason TEXT,
    ip_banned_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS clans (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    name TEXT NOT NULL,
    name_normalized TEXT NOT NULL UNIQUE,
    leader_character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE RESTRICT,
    alignment TEXT NOT NULL CHECK (alignment IN ('citizen', 'criminal')),
    min_join_level INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS clan_members (
    clan_id TEXT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
    character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('leader', 'co_leader', 'member')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (clan_id, character_id),
    UNIQUE (character_id)
);

CREATE TABLE IF NOT EXISTS clan_requests (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    clan_id TEXT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
    character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (character_id)
);

CREATE TABLE IF NOT EXISTS character_items (
    character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    id_pos INTEGER NOT NULL,
    id_item INTEGER NOT NULL,
    cant INTEGER NOT NULL DEFAULT 0,
    equipped BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (character_id, id_pos)
);

CREATE TABLE IF NOT EXISTS character_bank_items (
    character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    id_pos INTEGER NOT NULL,
    id_item INTEGER NOT NULL,
    cant INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (character_id, id_pos)
);

CREATE TABLE IF NOT EXISTS account_vaults (
    account_id TEXT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
    gold INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS account_vault_items (
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    id_pos INTEGER NOT NULL,
    id_item INTEGER NOT NULL,
    cant INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (account_id, id_pos)
);

CREATE TABLE IF NOT EXISTS clan_vaults (
    clan_id TEXT PRIMARY KEY REFERENCES clans(id) ON DELETE CASCADE,
    gold INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS clan_vault_items (
    clan_id TEXT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
    id_pos INTEGER NOT NULL,
    id_item INTEGER NOT NULL,
    cant INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (clan_id, id_pos)
);

CREATE TABLE IF NOT EXISTS character_spells (
    character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    id_pos INTEGER NOT NULL,
    id_spell INTEGER NOT NULL,
    PRIMARY KEY (character_id, id_pos)
);

CREATE TABLE IF NOT EXISTS character_settings (
    character_id TEXT PRIMARY KEY REFERENCES characters(id) ON DELETE CASCADE,
    hotkeys JSONB NOT NULL DEFAULT '{}',
    macros JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS market_listings (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    seller_character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    seller_name TEXT NOT NULL,
    item_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price INTEGER NOT NULL CHECK (price > 0),
    publication_fee INTEGER NOT NULL DEFAULT 0 CHECK (publication_fee >= 0),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'sold', 'expired', 'cancelled')),
    buyer_character_id TEXT REFERENCES characters(id) ON DELETE SET NULL,
    buyer_name TEXT,
    expires_at TIMESTAMPTZ NOT NULL,
    sold_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS market_claims (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    owner_character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    claim_type TEXT NOT NULL CHECK (claim_type IN ('gold', 'item')),
    gold_amount INTEGER NOT NULL DEFAULT 0 CHECK (gold_amount >= 0),
    item_id INTEGER,
    item_quantity INTEGER,
    source_listing_id TEXT REFERENCES market_listings(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (
        (claim_type = 'gold' AND gold_amount > 0 AND item_id IS NULL AND item_quantity IS NULL)
        OR (claim_type = 'item' AND gold_amount = 0 AND item_id IS NOT NULL AND item_quantity IS NOT NULL AND item_quantity > 0)
    )
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    selected_character_id TEXT REFERENCES characters(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    requested_ip TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS password_reset_requests (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    email_hash TEXT NOT NULL,
    requested_ip TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS game_tickets (
    ticket TEXT PRIMARY KEY,
    auth_token TEXT NOT NULL REFERENCES auth_sessions(token) ON DELETE CASCADE,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    character_id TEXT REFERENCES characters(id) ON DELETE CASCADE,
    mode TEXT NOT NULL DEFAULT 'world',
    arena_room_id TEXT,
    pvp_template_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS arena_rooms (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    owner_account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    password_hash TEXT,
    join_token TEXT NOT NULL UNIQUE,
    map_id INTEGER NOT NULL DEFAULT 272,
    capacity INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS arena_room_members (
    room_id TEXT NOT NULL REFERENCES arena_rooms(id) ON DELETE CASCADE,
    account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    selected_pvp_template_id INTEGER,
    connected BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (room_id, account_id)
);

CREATE TABLE IF NOT EXISTS user_online_stats (
    sampled_minute TIMESTAMPTZ PRIMARY KEY,
    total_users INTEGER NOT NULL,
    pve_users INTEGER NOT NULL,
    pvp_users INTEGER NOT NULL,
    fishing_users INTEGER NOT NULL,
    mining_users INTEGER NOT NULL DEFAULT 0,
    woodcutting_users INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS challenge_history (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    match_id TEXT NOT NULL UNIQUE,
    team_size INTEGER NOT NULL CHECK (team_size IN (1, 2)),
    instance_map_id INTEGER NOT NULL,
    winner_side INTEGER NOT NULL CHECK (winner_side IN (1, 2)),
    finish_reason TEXT,
    team_one_score INTEGER NOT NULL DEFAULT 0 CHECK (team_one_score >= 0),
    team_two_score INTEGER NOT NULL DEFAULT 0 CHECK (team_two_score >= 0),
    participants JSONB NOT NULL DEFAULT '[]',
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS runtime_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS site_config (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL DEFAULT '{}',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS game_objects (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    obj_type INTEGER NOT NULL,
    data JSONB NOT NULL,
    checksum TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    updated_by_account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS game_npcs (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    npc_type INTEGER NOT NULL,
    id_head INTEGER NOT NULL,
    id_body INTEGER NOT NULL,
    movement INTEGER NOT NULL,
    data JSONB NOT NULL,
    checksum TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    updated_by_account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS game_crafting_recipes (
    id INTEGER PRIMARY KEY,
    profession TEXT NOT NULL,
    category TEXT NOT NULL,
    item_id INTEGER NOT NULL,
    skill INTEGER NOT NULL,
    data JSONB NOT NULL,
    checksum TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    updated_by_account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS game_smelting_recipes (
    id INTEGER PRIMARY KEY,
    mineral_item_id INTEGER NOT NULL,
    ingot_item_id INTEGER NOT NULL,
    required_skill INTEGER NOT NULL,
    minerals_per_ingot INTEGER NOT NULL,
    data JSONB NOT NULL,
    checksum TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    updated_by_account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS game_balance (
    id INTEGER PRIMARY KEY,
    data JSONB NOT NULL,
    checksum TEXT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    updated_by_account_id TEXT REFERENCES accounts(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS game_data_revisions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL CHECK (kind IN ('objs', 'npcs', 'crafting_recipes', 'smelting_recipes', 'balance')),
    entity_id INTEGER NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('upsert')),
    checksum TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_clans_leader_character_id ON clans(leader_character_id);
CREATE INDEX IF NOT EXISTS idx_characters_clan_id ON characters(clan_id);
CREATE INDEX IF NOT EXISTS idx_clan_members_clan_id ON clan_members(clan_id);
CREATE INDEX IF NOT EXISTS idx_clan_requests_clan_id ON clan_requests(clan_id);

CREATE INDEX IF NOT EXISTS idx_market_listings_status_price_created
    ON market_listings(status, price ASC, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_market_listings_active_price_created
    ON market_listings(price ASC, created_at ASC)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_market_listings_item_status_price
    ON market_listings(item_id, status, price ASC, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_market_listings_seller_status
    ON market_listings(seller_character_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_market_listings_seller_active_created
    ON market_listings(seller_character_id, created_at DESC)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_market_listings_expires_at_active
    ON market_listings(expires_at)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_market_claims_owner_created
    ON market_claims(owner_character_id, created_at ASC);

-- Correo entre jugadores (VB6 ModCorreo.bas / charfile [CORREO]): mensajes
-- con remitente, texto, items adjuntos serializados ("objIndex-cantidad@"),
-- flag de leido y fecha en formato display del VB6.
CREATE TABLE IF NOT EXISTS character_correo (
    id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-8' || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
    character_id TEXT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    remitente TEXT NOT NULL,
    mensaje TEXT NOT NULL,
    item TEXT NOT NULL DEFAULT '',
    item_count INTEGER NOT NULL DEFAULT 0 CHECK (item_count >= 0),
    leido BOOLEAN NOT NULL DEFAULT FALSE,
    fecha TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_character_correo_character_created
    ON character_correo(character_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts(email);
CREATE INDEX IF NOT EXISTS idx_characters_account_id ON characters(account_id);
CREATE INDEX IF NOT EXISTS idx_characters_name ON characters(name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_characters_name_active_unique
    ON characters (LOWER(TRIM(name)))
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_characters_account_id_active
    ON characters(account_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_auth_sessions_account_id ON auth_sessions(account_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_account_id ON password_reset_tokens(account_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_email_hash_created_at ON password_reset_requests(email_hash, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_ip_created_at ON password_reset_requests(requested_ip, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_tickets_auth_token ON game_tickets(auth_token);
CREATE INDEX IF NOT EXISTS idx_game_tickets_expires_at ON game_tickets(expires_at);
CREATE INDEX IF NOT EXISTS idx_game_tickets_arena_room_id ON game_tickets(arena_room_id);
CREATE INDEX IF NOT EXISTS idx_arena_rooms_owner_account_id ON arena_rooms(owner_account_id);
CREATE INDEX IF NOT EXISTS idx_arena_rooms_is_public ON arena_rooms(is_public);
CREATE INDEX IF NOT EXISTS idx_arena_room_members_account_id ON arena_room_members(account_id);
CREATE INDEX IF NOT EXISTS idx_user_online_stats_created_at ON user_online_stats(created_at);
CREATE INDEX IF NOT EXISTS idx_game_objects_updated_at ON game_objects(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_objects_obj_type ON game_objects(obj_type);
CREATE INDEX IF NOT EXISTS idx_game_objects_name_lower ON game_objects(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_game_npcs_updated_at ON game_npcs(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_npcs_npc_type ON game_npcs(npc_type);
CREATE INDEX IF NOT EXISTS idx_game_npcs_name_lower ON game_npcs(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_game_crafting_recipes_updated_at ON game_crafting_recipes(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_crafting_recipes_profession ON game_crafting_recipes(profession);
CREATE INDEX IF NOT EXISTS idx_game_crafting_recipes_item_id ON game_crafting_recipes(item_id);
CREATE INDEX IF NOT EXISTS idx_game_smelting_recipes_updated_at ON game_smelting_recipes(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_smelting_recipes_mineral_item_id ON game_smelting_recipes(mineral_item_id);
CREATE INDEX IF NOT EXISTS idx_game_balance_updated_at ON game_balance(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_data_revisions_kind_id ON game_data_revisions(kind, id DESC);
CREATE INDEX IF NOT EXISTS idx_challenge_history_finished_at ON challenge_history(finished_at DESC);
